# Generated by Django 2.2.7 on 2019-11-30 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graduateProject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeRechargeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=8)),
                ('receipt_no', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('trade_dttm_webserver', models.DateTimeField()),
                ('trade_dttm_browser', models.DateTimeField()),
                ('delete_yn', models.CharField(default='N', max_length=1)),
                ('ins_dttm', models.DateTimeField(auto_now_add=True)),
                ('ins_user', models.CharField(default='ADMIN', max_length=20)),
                ('upt_dttm', models.DateTimeField(auto_now=True)),
                ('upt_user', models.CharField(default='ADMIN', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='graduateProject.User')),
            ],
        ),
    ]
