# Generated by Django 2.2.7 on 2019-12-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduateProject', '0003_liveinterviewmodel_reply_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveinterviewreplymodel',
            name='reply_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
