# Generated by Django 2.2.7 on 2019-12-02 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graduateProject', '0004_liveinterviewreplymodel_reply_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChattingRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1', models.IntegerField()),
                ('user2', models.IntegerField()),
                ('make_dttm', models.DateField()),
                ('delete_yn', models.CharField(default='N', max_length=1)),
                ('ins_dttm', models.DateTimeField(auto_now_add=True, null=True)),
                ('ins_user', models.CharField(default='ADMIN', max_length=20)),
                ('upt_dttm', models.DateTimeField(auto_now=True, null=True)),
                ('upt_user', models.CharField(default='ADMIN', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Chatting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('send_dttm', models.DateTimeField()),
                ('read_yn', models.CharField(max_length=1)),
                ('delete_yn', models.CharField(default='N', max_length=1)),
                ('ins_dttm', models.DateTimeField(auto_now_add=True, null=True)),
                ('ins_user', models.CharField(default='ADMIN', max_length=20)),
                ('upt_dttm', models.DateTimeField(auto_now=True, null=True)),
                ('upt_user', models.CharField(default='ADMIN', max_length=20)),
                ('chatting_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='graduateProject.ChattingRoom')),
                ('send_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='graduateProject.User')),
            ],
        ),
    ]
