# Generated by Django 2.2.7 on 2019-12-02 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graduateProject', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionRequestSearchModel',
        ),
    ]
