# Generated by Django 2.2.7 on 2019-12-02 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graduateProject', '0002_delete_questionrequestsearchmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionRequestSearchModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_h_category', models.CharField(max_length=3)),
                ('cat_m_category', models.CharField(max_length=3)),
                ('cat_key', models.CharField(max_length=3)),
                ('delete_yn', models.CharField(default='N', max_length=1)),
                ('ins_dttm', models.DateTimeField(auto_now_add=True, null=True)),
                ('ins_user', models.CharField(default='ADMIN', max_length=20)),
                ('upt_dttm', models.DateTimeField(auto_now=True, null=True)),
                ('upt_user', models.CharField(default='ADMIN', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='graduateProject.User')),
            ],
        ),
    ]
