# Generated by Django 2.2.7 on 2019-12-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduateProject', '0003_questionrequestsearchmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_flag', models.CharField(max_length=3)),
                ('tasktype_flag', models.CharField(max_length=3)),
                ('lifestyle_flag', models.CharField(max_length=3)),
                ('read_yn', models.CharField(max_length=1)),
                ('delete_yn', models.CharField(default='N', max_length=1)),
                ('ins_dttm', models.DateTimeField(auto_now_add=True, null=True)),
                ('ins_user', models.CharField(default='ADMIN', max_length=20)),
                ('upt_dttm', models.DateTimeField(auto_now=True, null=True)),
                ('upt_user', models.CharField(default='ADMIN', max_length=20)),
            ],
        ),
    ]
