# Generated by Django 2.2.7 on 2019-12-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduateProject', '0004_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='field_flag',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='document',
            name='lifestyle_flag',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='document',
            name='tasktype_flag',
            field=models.IntegerField(),
        ),
    ]
