# Generated by Django 2.2.7 on 2019-12-04 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graduateProject', '0005_auto_20191204_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='field_flag',
            new_name='category1',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='lifestyle_flag',
            new_name='category2',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='tasktype_flag',
            new_name='category3',
        ),
    ]
